### ISSUE TITLE
args and kwargs are not recognized as generic arguments

### ISSUE THREAD

**Issue by JenniferHem** [jshwi/docsig#113]
Hi,

I just came across an error (or expected behavior?):

I have the Fuction with the docstring
```
def mocked_requests_get(*args: str, **kwargs: str) -> Response:
    """Mock the expected Response from the API based on the received url via args.

    Returns
    -------
    Response
        response object
    """
```
which leads to the Error:
```
def mocked_requests_get(✖*args, ✖**kwargs) -> ✓Response:
    """
    :param None: ✖
    :param None: ✖
    :return: ✓
    """
E103: parameters missing
```

Not sure if this should be the case usually I would not annotate args/kwargs as they are no specific function arguments. Or is my notion wrong here?

We are using numpy type docstrings in case this is relevant. Happy to provide more info if I forgot anything relevant.

**Comment by jshwi** [comment]
Hi @JenniferHem , thank you for helping to make this package better by opening this issue!

I will look at this as soon as I have a spare moment, and provide an update soon 😄

**Comment by jshwi** [comment]
Hi @JenniferHem,
Just got round to this one and I realise what you're after
Luckily #48 was already been raised for this kind of workflow
I annotate my args and kwargs, if you don't you can use ` -a/--ignore-args` and `-k/--ignore-kwargs` 😄 
I'll close this one, thank you, and hope this works for you
Any more things come to mind please don't hesitate to let me know
Stephen
