### ISSUE TITLE
Support for Numpy

### ISSUE THREAD

**Issue by hhalaby** [jshwi/docsig#14]
Hello @jshwi 
Any plans to add support for Numpy style docstring?

**Comment by jshwi** [comment]
Hi @hhalaby, I would base the priority for other styles of docstring on demand, so thank you for opening this issue. Considering you've shown interest in support for `numpy` I will see what I can do (a formatter that can evaluate different syntax rules would be helpful for extensibility). If you have any ideas as well I always welcome a pull request.

**Comment by jshwi** [comment]
Hi @hhalaby feel free to clone and try out this branch, I've added unittests, but haven't got any numpy docstrings to test it on live, would appreciate any feedback if you find the time

**Comment by jshwi** [comment]
@hhalaby I'll merge this one for now, feel free to reopen if you find anything amiss
