### ISSUE TITLE
Sphinx 7.0 compatibility

### ISSUE THREAD

**Issue by EFord36** [jshwi/docsig#224]
Hi,

At the moment, `docsig` declares a dependency of:

`Sphinx = ">=4.3.2,<7.0.0"`

which means you can't install `docsig` in the same virtual environment as a project that wants to build it's own docs with Sphinx 7.0 or greater.

However, from a quick look, it doesn't seem like it needs to rule out `7.0.0` for the correct operation of `docsig` - the only place I can see `sphinx` used from a quick search is as `import sphinx.ext.napoleon as _s` in `docsig/_function.py`, and even there, it's the Napoleon extension specifically, and it doesn't look to me that the way it's used would be broken by 7.0.

I'm guessing you want to restrict to `<7.0.0` for building the docs of `docsig`, but could that be done as a `dev` dependency, and the 'main' dependency just be `Sphinx = `>=4.3.2` or similar?

This isn't affecting me directly (it was, but I just changed my pre-commit config so `docsig` got installed in its own virtual environment rather than as a 'local' hook, which is best practice anyway).

Let me know what you think, and if you think there is work (beyond the normal testing of PRs etc.) to support sphinx 7, I can potentially pick it up

**Comment by jshwi** [comment]
Hey @EFord36 ,

How's it going, thanks mate for opening this

Looks like this wasn't a decision of mine, appears that's how dependabot likes to do things 😄 
```
docsig on  master [$] is 📦 v0.43.0 via ⬢ v21.2.0 via docsig-rMEOAeFU-py3.8 via 🐍 3.8.13
➜ git blame pyproject.toml | cat | grep -i 'sphinx ='
c69069f9 (dependabot[bot]  2023-03-20 05:12:45 +0000  77) Sphinx = ">=4.3.2,<7.0.0"
```
```
docsig on  master [$] is 📦 v0.43.0 via ⬢ v21.2.0 via docsig-rMEOAeFU-py3.8 via 🐍 3.8.13
➜ git diff c69069f9\~ c69069f9 -- pyproject.toml | cat | grep -i 'sphinx ='
-Sphinx = "^4.3.2"
+Sphinx = ">=4.3.2,<7.0.0"
```
I don't think this is to do with docs, at least I can see an issue with the docs

Happy to bump this, it doesn't look like it breaks anything

Should this be released on it's own, or just with the next release? Is there any urgency, or would this be a long term change?

**Comment by EFord36** [comment]
no urgency from me - I'd probably say wait for the next release.

Thanks for the quick response!

**Comment by jshwi** [comment]
No worries at all, just finished up for the day so thought I'd check in

**Comment by jshwi** [comment]
any issues let me know 😄
