### ISSUE TITLE
Support for Python 3.7.x

### ISSUE THREAD

**Issue by rcisterna** [jshwi/docsig#3]
Hey @jshwi! I came across this tool because of a comment of yours on [StackOverflow](https://stackoverflow.com/a/72785806). I wanted to use your tool for a small project that I'm currently working on, but [poetry](https://python-poetry.org/) cannot resolve the dependencies because my tool is built for Python 3.7.2+, and yours for 3.8+.

Is there a reason for not to support Python 3.7? If so, is there anything I can do to help add support for it?

**Comment by jshwi** [comment]
Hey @rcisterna, just looked into this, there is a bit of a dependency hell going on with lowering the min python version to 3.7.

3.7 is end of life in 11 months, I'll have to look into this some more to confirm whether this would be a worthwhile change.

**Comment by rcisterna** [comment]
Hey @jshwi! Thanks for your answers!

You are right about the EOL of 3.7.x, I should have checked that first. Anyway, I'll take a quick look at this as well, but if it requires too much effort I don't think it's worth it for just eleven months.

**Comment by jshwi** [comment]
I'll close @rcisterna, I won't get round to supporting 3.7 personally, but this will continue to work with >=3.8.
Thanks for the interest, if you ever got round to it I'd be happy to review a PR
