### ISSUE TITLE
Optinal return statements with overload function result in docsig error E104

### ISSUE THREAD

**Issue by conrad-stork-basf** [jshwi/docsig#318]
Hi @jshwi,

we have again found a (from our perspective) weird behavior of docsig. The issue occurs when we define different return types with overload functions. I have prepared a minimal example:
```python
from typing import Optional, overload


@overload
def get_something(number: int) -> str:
    """For getting a string from an integer."""


@overload
def get_something(number: None) -> None:
    """For getting a string from an integer."""


def get_something(number: Optional[int]) -> Optional[str]:
    """
    For getting a string from an integer.

    Parameters
    ----------
    number : int
        The number to convert to a string.

    Returns
    -------
    str
        The string representation of the number.
    """
    if number is None:
        return None
    return str(number)
```

We call docsig with the following command: `docsig -C -m -N -o -p -P test.py`

Perhaps you can comment on that. We think that no error in that case should be raised.

Thanks in advance and Best
Conrad

**Comment by jshwi** [comment]
Hi @conrad-stork-basf, you're right, I'll push a fix now and it'll be available with v0.53.1

Thanks for spotting that!
