### ISSUE TITLE
Parameter and return value is not correctly recognized

### ISSUE THREAD

**Issue by JenniferHem** [jshwi/docsig#36]
Hey I just came across the project and would love to use it for larger projects to avoid faulty documentation after e.g. refactoring of code. 
Now I have a function:

```
def modify(numericString: Union[str, int]) -> str:
    '''Do stuff.

    Parameters
    ----------
    numericString: Union[str, int]
        numeric string that should be converted.

    Returns
    -------
    str
        reformatted string
    '''
    numericString = str(numericString)
    last = numericString[-1]
    middle = numericString[-3:-1]
    first = numericString[:-3]
    finalstring = "-".join([first, middle, last])
    return finalstring 
```

Now I get the error:

```
def modify(✖numericString) -> ✓str:
    """...

    :param None: ✖
    :return: ✓
    """

E103: parameters missing
```

Another example I encountered:

```
def check_stuff(str_lin: str) -> bool:
    """Check if "A" or "B".

    The function checks wether the string is "A" or "B".

    Parameters
    ----------
    str_lin: str
        special string produced by function_of_y

    Returns
    -------
    bool
        Returns True, else false
    """
    if any(s in str_lin for s in ["A", "B"]):
        return True
    return False
```

The error:

```
def check_stuff(✖str_lin) -> ✖bool:
    """...

    :param None: ✖
    :return: ✖
    """

E103: parameters missing
E105: return missing from docstring
```

I am a bit confused as I cannot really pinpoint the issue. Is this a parsing or formatting problem of the docstring? Any obvious error here? 
Please ignore the random weird functions, they are just examples similar to conde I have written.

**Comment by jshwi** [comment]
Hi @JenniferHem, thank you for opening this issue, appears to be a problem with the way indents are handled with numpy style docs, I'll look into this as soon as I can

**Comment by jshwi** [comment]
Actually for the first one, `Returns` being an indicator of a numpy docstring, that's been fixed in v0.23.1, yet to look at the other examples

**Comment by jshwi** [comment]
Hi @JenniferHem

The `numpy` parser was too strict with indents and whitespace

Those examples now pass and you can clone or `pip install docsig==0.23.2`

If you find anything else please keep opening issues or PRs so long as you find use for this! I don't use `numpy` style, so issues like this help a lot

**Comment by jshwi** [comment]
@JenniferHem.
`numpy` was pretty buggy and not very usable, you should see some positive results with the latest version (`v0.24.0`), It's at least as usable as RST, which works well for me

**Comment by JenniferHem** [comment]
I can confirm that your fixes solved the mentioned errors and I see it working as expected. Thank you very much for the quick fix(es)!

**Comment by JenniferHem** [comment]
Okay not sure if it is intended so not re-opening I just saw an issue with: 
```
def check_stuff(str_lin: str, a: str) -> bool:
    """Check if "A" or "B".

    The function checks wether the string is "A" or "B".

    Parameters
    ----------
    str_lin: str
        special string produced by function_of_y ["a"]
            a second wrong indent line
    a: str
        string stuff

    Returns
    -------
    bool
        Returns True, else false
    """
    if any(s in str_lin for s in ["A", "B"]):
        return True
    return False
```

Here I get the error: 

```
def check_stuff(✖str_lin, ✖a) -> ✓bool:
    """...

    :param a: ✖
    :param None: ✖
    :return: ✓
    """

E103: parameters missing
hint: there appears to be a syntax error that could be causing this
E101: parameters out of order
```

which definitely helped me to spot the wrong indent. 

I am just not 100% sure if the indent should cause this (might be specific functionalities of docs related that I am not aware?) or if this should not fail when parsing?

This is definitely a style problem which should not occur, just thought I'd run it by you to get your opinion how you want to handle this!

**Comment by jshwi** [comment]
Hi @JenniferHem

The result is quite confusing, I understand
As the param was not even parsed due to the indentation it resulted in a missing parameter
The None value was parsed after iterating through the longest so it also resulted in an incorrect error for ordering
A new error has been added
```
E115: syntax error in description
```
Which gives you more control over this result
If you don't care about syntax errors in the description you can disable the check
This is available with ^0.26.0

Thanks again 😄

**Comment by JenniferHem** [comment]
Amazing thanks!

**Comment by jshwi** [comment]
No worries @JenniferHem, happy you have found this useful 😄
