### ISSUE TITLE
v0.59.0 fails with UnicodeDecodeError

### ISSUE THREAD

**Issue by c-w-feldmann** [jshwi/docsig#384]
Hey, thanks for providing this cool tool!

Our github workflow utilzes docsig and so far, it worked smoothly. After upgrading to 0.59.0 we get this error:

```bash
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
```
 You can the the original error [here](https://github.com/basf/MolPipeline/actions/runs/9957935450/job/27511088363#step:5:8)

Since it worked so far, I guess this is a bug. Unfortunately, I cannot test this locally right now, so I am not able to find a minimal example.
I hope I can provide this in the next days.

Environment:

- Python version: 3.11.9
- docsig version: 0.59.0

**Comment by jshwi** [comment]
Hey @c-w-feldmann 
Thanks heaps for spotting this, and particularly for taking the time to let me know
I can see what went wrong, and I'm going to patch this up now
0.59.1 will have this resolved
Cheers!
Stephen
