### ISSUE TITLE
Feature request - pre-commit integration & links

### ISSUE THREAD

**Issue by Laleee** [jshwi/docsig#39]
# Feature request

I realy like this library and find that it has some features that are missing in the pydocstyle. :tada:

### Feature 1 :rocket:

Since many users automate linters, it would be nice to have support for the pre-commit. :)

### Feature 2 :rocket:

When path to a file is displayed, it would be nice if it was a link to the specific line (like in pydocstyle). I'm using PyCharm if that's of any relevance.

**Comment by jshwi** [comment]
Hi @Laleee, thank you for the positive feedback

I'll like to have a look at this, feature 2 is a really good idea,  it won't be hard to implement. I should be able to put that together pretty quickly

I'll look at feature 1 pre-commit integration too, once I complete 2

Thank you for helping improve this package!

**Comment by jshwi** [comment]
1 and 2 should be all good, if anything else comes to mind please don't hesitate to let me know, cheers!

**Comment by Laleee** [comment]
Hi @jshwi,

Just wanted to confirm that everything works as expected.

Great work!

**Comment by jshwi** [comment]
Awesome! thanks for confirming @Laleee!
