### ISSUE TITLE
exclude cannot handle directory 

### ISSUE THREAD

**Issue by LisPrzemyslaw** [jshwi/docsig#392]
The exclude files cannot hold the whole dictionary. The regex pattern checks only for the name of the file so in a case that you have 2 similar file names but in different folders then you have to exclude both.

Replace bug:
In my case I'm using poetry so the config file looks like this:
pyproject.toml
```
[tool.docsig]
exclude = '''.*src\\design\\.*'''
```
The design folder should be excluded. But it is not. This line makes nothing.

Expected:
The whole folder is not in checks.

Possible solution:
right now in _files.py::Paths::_populate there is a regex match `_re.match(i, root.name)` and to proper work it should be a `_re.match(i, str(name))` This will allows to check whole folders instead of only one file. It is really important if you have the same names in different folders and only one should be excluded.

Environment:

- Python version: 3.11.4
- docsig version: 0.59.1

**Comment by jshwi** [comment]
Hey @LisPrzemyslaw 
Thanks for opening this and making the logic behind this flawed regex handling known
Are you able to check this branch and let me know how the fix looks on your end?
Cheers,
Stephen

**Comment by jshwi** [comment]
@LisPrzemyslaw , I'm pretty satisfied this is fixed now, I tried on mac and my windows vm
I'll make this available now as v0.59.2
Any issues please don't hesitate to let me know

**Comment by LisPrzemyslaw** [comment]
I've tested it and it is working.

@jshwi thanks a lot! Good job! 🚀

**Comment by jshwi** [comment]
Awesome, no worries at all @LisPrzemyslaw ! Thanks for confirming 😄
