### ISSUE TITLE
Report when the parameter is spelled wrongly

### ISSUE THREAD

**Issue by ronnyerrmann** [jshwi/docsig#4]
```
somemethod(myparam) -> str:
    """ What the method does
    :param nottherightparam: what the param does
    :return: str
    """
```
is not reported in version 0.13.0. However, if another mistake is added, e.g. I remove the return type hint and cause a E109, then the output shows that the parameter is wrong.

And a minor thing: `docsig -v` doesn't return anything, but `docsig --version` works

**Comment by jshwi** [comment]
Added #5 for the `-v` flag, thank you spotting that one

**Comment by jshwi** [comment]
Hi @ronnyerrmann, hopefully #7 resolves this issue

**Comment by jshwi** [comment]
@ronnyerrmann  I'll merge and release this PR. Feel free to reopen if you have any concerns. Cheers!
