### ISSUE TITLE
Skip checking for one line docstings

### ISSUE THREAD

**Issue by Laleee** [jshwi/docsig#45]
Hello,

It would be good if checking could be skipped somehow for one line docstrings. 

For example

```python3
def example(some_input: int) -> int:
    """Return input."""
    return some_input
```

Sometimes the effort to write the full doctoring is just too high. This is also fine with the linter pydocstyle.

Would you consider adding an option to ignore docstrings that are in one line?

**Comment by jshwi** [comment]
Hi @Laleee, I can look at this, I don't see why that couldn't be an option! Let me see what I can do. Cheers!

**Comment by jshwi** [comment]
@Laleee, that should do it
While it won't take into consideration whether the docstring is one line or several, it will ignore docstrings containing no parameter documentation, which will do what you want it to in that example
