### ISSUE TITLE
Import error on `sphinxcontrib.napoleon` on Python 3.10.8

### ISSUE THREAD

**Issue by sebastian-correa** [jshwi/docsig#65]
Hey! I'm getting this `ImportError` when running `docsig --help`:
```python
ImportError: cannot import name 'Callable' from 'collections'
```

`docsig` requires `sphinxcontrb-napoleon` [directly](https://github.com/jshwi/docsig/blob/2e4c4d0b09ba795031feb3da13051365fd2f72e3/pyproject.toml#L81), to its latest version of `0.7` which was released in [_2018_](https://pypi.org/project/sphinxcontrib-napoleon/#history).

As seen in [this](https://github.com/sphinx-contrib/napoleon/commit/572de996794305117443a9c29118c6781f2b3ad2) commit to `sphinxcontrib-napoleon`, the issue I'm facing was fixed in 2021. I tried copy-pasting that commit into my `venv` and `docsig --help` ran correctly.

I see 2 alternatives:
1. Given that `napoleon` now comes bundled with `sphinx` (at `sphinx.ext.napoleon`), `docsig` should have a direct requirement on `sphinx`. `sphinx` is quite big, though, and you may not want this.
2. Specify a `git` dependency [[ref](https://python-poetry.org/docs/dependency-specification/#git-dependencies)] for `sphinxcontrib-napoleon`, knowing that that repo is not kept up to date.

I can work on a PR to fix this with whatever solution you prefer.

**Comment by sebastian-correa** [comment]
I tried a simple replacement in `_function.py` (changed import to `import sphinx.ext.napoleon as _s`) and many tests are failing. I don't have experience with `pytest` nor `docsig`, so fixing these seems a tall order.
```
=========================== short test summary info ============================
FAILED tests/_test.py::test_ignore_no_params[f-e-1-0-4-ret-type-docs-1-sum-n-i] - AssertionError: assert ('E104: return statement documented for None' in '' ...
FAILED tests/_test.py::test_main_sum[f-e-1-0-4-ret-type-docs-1-sum-n-i] - AssertionError: assert 0 == 1
FAILED tests/_test.py::test_ignore_no_params[f-no-ret-docs-no-type-n-i] - assert ('def function(✓param1, ✓param2, ✓param3)?:\n    """\n    :param par...
FAILED tests/_test.py::test_main_output_negative[f-no-ret-docs-no-type-n-i] - assert 'def function(✓param1, ✓param2, ✓param3)?:\n    """\n    :param para...
FAILED tests/_test.py::test_main_str_out[f-no-ret-docs-no-type-n-i] - assert 'def function(✓param1, ✓param2, ✓param3)?:\n    """\n    :param para...
FAILED tests/_test.py::test_ignore_kwargs[f-e-1-0-4-ret-type-docs-1-sum-n] - AssertionError: assert 0 == 1
FAILED tests/_test.py::test_main_str[f-e-1-0-4-ret-type-docs-1-sum-n] - assert 0 == 1
FAILED tests/_test.py::test_main_output_negative[4RET2] - assert 'E104: return statement documented for None' in ''
FAILED tests/_test.py::test_ignore_no_params[f-no-ret-docs-no-type-n] - assert ('def function(✓param1, ✓param2, ✓param3)?:\n    """\n    :param par...
FAILED tests/_test.py::test_main_args[f-e-1-0-4-ret-type-docs-1-sum-n] - AssertionError: assert 0 == 1
FAILED tests/_test.py::test_main_args[f-e-1-0-4-ret-type-docs-1-sum-n-i] - AssertionError: assert 0 == 1
FAILED tests/_test.py::test_ignore_args[f-e-1-0-4-ret-type-docs-1-sum-n-i] - AssertionError: assert 0 == 1
FAILED tests/_test.py::test_ignore_no_params[f-e-1-0-4-ret-type-docs-1-sum-n] - AssertionError: assert ('E104: return statement documented for None' in '' ...
FAILED tests/_test.py::test_main_str_out[4RET1] - assert 'E104: return statement documented for None' in ''
FAILED tests/_test.py::test_main_str_out[f-no-ret-docs-no-type-n] - assert 'def function(✓param1, ✓param2, ✓param3)?:\n    """\n    :param para...
FAILED tests/_test.py::test_ignore_kwargs[f-e-1-0-4-ret-type-docs-1-sum-n-i] - AssertionError: assert 0 == 1
FAILED tests/_test.py::test_main_output_negative[f-no-ret-docs-no-type-n] - assert 'def function(✓param1, ✓param2, ✓param3)?:\n    """\n    :param para...
FAILED tests/_test.py::test_main_str_out[4RET2] - assert 'E104: return statement documented for None' in ''
FAILED tests/_test.py::test_main_sum[f-e-1-0-4-ret-type-docs-1-sum-n] - AssertionError: assert 0 == 1
FAILED tests/_test.py::test_main_output_negative[4RET1] - assert 'E104: return statement documented for None' in ''
FAILED tests/_test.py::test_ignore_args[f-e-1-0-4-ret-type-docs-1-sum-n] - AssertionError: assert 0 == 1
FAILED tests/_test.py::test_main_str[f-e-1-0-4-ret-type-docs-1-sum-n-i] - assert 0 == 1
```

**Comment by jshwi** [comment]
Hi @sebastian-correa,
Thank you for spotting this
I welcome a PR if you find a solution
I will also have a look when I get a moment
Cheers

**Comment by sebastian-correa** [comment]
I don't know what's up with my out-of-order comment. I saw the release; that was blazing fast! I'm sorry I couldn't submit a PR with a fix, but I will continue implementing `docsig` into our codebase.

**Comment by jshwi** [comment]
Hi @sebastian-correa,

You helped hurry along this release with the reading up you did on this

I wanted this to work quicker for you so I went ahead with the release, as I knew what the issue was, based on my knowledge of this code

I'll see if I can put together a CONTRIBUTING.md together to make it easier for you to navigate the codebase if you ever want to submit a PR

Also, next time if you find something here, I would be happy for you to make a WIP PR, even if it fails, and we could discuss it

Thanks for the support!

Stephen
